name: Pulumi Deployment

on:
  push:
    branches:
      - main
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Install Pulumi
      run: |
        curl -fsSL https://get.pulumi.com | sh
        export PATH=$PATH:$HOME/.pulumi/bin
    
    - name: Determine deployment environment
      id: stack
      run: |
        if [[ ${{ github.ref }} == 'refs/heads/main' ]]; then
          echo "::set-output name=stack::prod"
        elif [[ ${{ github.ref }} == 'refs/heads/staging' ]]; then
          echo "::set-output name=stack::staging"
        else:
          echo "Not on a deployable branch. Exiting."
          exit 0
        fi
    
    - name: Pulumi login
      run: pulumi login --non-interactive --cloud-url ${PULUMI_ACCESS_TOKEN}
      env:
        PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Pulumi deploy
      run: |
        pulumi stack select ${{ steps.stack.outputs.stack }}
        pulumi up --yes
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
